TITLE_FONT = ('Comic Sans MS', 30, 'bold')
MEDIUM_FONT = ('Arial', 12, '')
MEDIUM_BOLD = ('Arial', 14, 'bold')
SMALL_FONT = ('Arial', 10, '')
SMALL_BOLD = ('Arial', 10, 'bold')
UNDERLINE_SMALL = ('Comic Sans MS', 10, 'underline')
UNDERLINE_MEDIUM = ('Comic Sans MS', 14, 'underline')
